# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acacb3d9981205be861a7ec114bb470a8d3a046de1703f5edfbd115379e8ed231c33dbacce1ffbf8bc8ea8a65d552e515d7036516f5ffd47a7428905d017fa5d

test:
  secret_key_base: 331126dd47fbd11943a58f144e935d96af63d3ac7f0bd3eb2943c5fdd23dbf5245d4ef60ff2ba230e507cfd91d6b0c50320e44b2feeaa5e2ef7c5bf22e710ab1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
